title: Graziella Lancia
author: Graziella Lancia
email: graziella.lancia@gmail.com 
description: ""
#description: >-
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

social:
  instagram: graziellalancia
#  twitter: joaomlneto
#  facebook: joaomlneto
#  github: joaomlneto
#  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
